### ISSUE TITLE
Error: java: io.kaitai.struct.KaitaiStream is abstract; cannot be instantiated

### ISSUE THREAD

**Issue by bulbum** [kaitai-io/kaitai_struct_compiler#102]
I compiled a few classes into Java. I added them to my project (IntelliJ IDEA). I also took a 

- KaitaiStream.java
- KaitaiStruct.java
- ByteBufferKaitaiStream.java
- RandomAccessFileKaitaiStream.java

from [here](https://github.com/kaitai-io/kaitai_struct_java_runtime/tree/48322f4ca62a32ccb56453fc8285822c8fbfe5d2/src/main/java/io/kaitai/struct). And there were errors in every class, such as:

```
public class Pcap extends KaitaiStruct {
    public static Pcap fromFile(String fileName) throws IOException {
        return new Pcap(new KaitaiStream(fileName)); // - 'KaitaiStream is abstract; cannot be instantiated
    }
```

Screenshot you may see here: https://pp.userapi.com/c836231/v836231283/5a83c/zQcqBjeHcz8.jpg

_______________________________________

Я скомпилировал несколько классов на Java. Взял всю папку, добавил в свой проект (IntelliJ IDEA). Также, на [официальном сайте ](http://kaitai.io/) говорится, что в проект необходимо добавить runtime library. Их я взял вот [отсюда](https://github.com/kaitai-io/kaitai_struct_java_runtime/tree/48322f4ca62a32ccb56453fc8285822c8fbfe5d2/src/main/java/io/kaitai/struct). Однако, при первой же попытке скомпилировать начались проблемы. С именами пакетов проблем нет - всё корректно. 

Скриншот: https://pp.userapi.com/c836231/v836231283/5a83c/zQcqBjeHcz8.jpg

**Comment by GreyCat** [comment]
There is version mismatch between ksc (and its output) vs runtime. Judging by the error message, you've used ksc v0.7, but a more modern runtime from v0.8. Please use either v0.7 everywhere or v0.8 (i.e. latest from git) everywhere.

You can download 0.7 runtime from Maven Central repo, or from [0.7 tag](https://github.com/kaitai-io/kaitai_struct_java_runtime/tree/0.7) in runtime repo.

**Comment by bulbum** [comment]
Now I realized, it's better to add not source code, but libraries. I added to the project two jar files kaitai-struct-runtime-0.8-20170724.080325-1.jar and kaitai-struct-runtime-0.8-20170724.080325-1-sources.jar as libraries, [from here](https://oss.sonatype.org/content/repositories/snapshots/io/kaitai/kaitai-struct-runtime/0.8-SNAPSHOT/), but the error still remains. It claims that KaitaiStream is abstract.

_______________________________________________

Насколько я понял, добавлять следует не как исходные коды, а как библиотеку. Добавил как библиотеку в свой проект jar-файлы kaitai-struct-runtime-0.8-20170724.080325-1.jar и kaitai-struct-runtime-0.8-20170724.080325-1-sources.jar [отсюда](https://oss.sonatype.org/content/repositories/snapshots/io/kaitai/kaitai-struct-runtime/0.8-SNAPSHOT/). Однако ошибка та же. Утверждает, что KaitaiStream is abstract.

**Comment by GreyCat** [comment]
It doesn't matter if you use source .java files or a precompiled jar bundle - just use the right version :)

**Comment by bulbum** [comment]
Yes, it works! Thank you!
