### ISSUE TITLE
Compiler as a gradle/maven plugin 

### ISSUE THREAD

**Issue by jvmlet** [kaitai-io/kaitai_struct_compiler#103]
Hi
What is the best way to automate the generation of classes/structs ?
The  gradle/maven plugins seem to be the way to go... Are they exist ?

**Comment by jvmlet** [comment]
If you bundle the compiler as executable jar it would be great and easy the integraition with build  tools

**Comment by GreyCat** [comment]
Moved to https://github.com/kaitai-io/kaitai_struct/issues/223
