### ISSUE TITLE
Maven plugin?

### ISSUE THREAD

**Issue by daviderickson** [kaitai-io/kaitai_struct_compiler#117]
Hi do you have any plans to release this compiler for use in maven builds?  I'd really like to automatically (re)generate java source files based on the core ksy file as part of my build process, and a small maven plugin that does this would be fantastic.

Thanks!

**Comment by GreyCat** [comment]
There seem to be already a request for that: https://github.com/kaitai-io/kaitai_struct/issues/223
Also, please do not create issues in this project, create them in [main project](https://github.com/kaitai-io/kaitai_struct/issues/) instead.

**Comment by daviderickson** [comment]
Sorry about that, wasn't aware of where to file.  Thanks!

**Comment by GreyCat** [comment]
No worries :) Feel free to continue discussion, try whatever's proposed in that ticket, and/or contribute better Maven plugin.
