### ISSUE TITLE
Compilation on GNU/Linux

### ISSUE THREAD

**Issue by CarelessChaser** [kaitai-io/kaitai_struct_compiler#12]
I've downloaded sources kaitai-struct-compiler-0.4.tar.gz and installed sbt.
What commands I need to compile project from scratch for general GNU/Linux?
I want to get same result as "universal" build.
Thanks.

**Comment by GreyCat** [comment]
That would be `sbt compilerJVM/universal:packageBin` — you'll get the result in `jvm/target/universal/kaitai-struct-compiler-0.4.zip`.

For more details, please take a look at [DEVELOPERS.md](https://github.com/kaitai-io/kaitai_struct_compiler/blob/master/DEVELOPERS.md) and our [testing framework](https://github.com/kaitai-io/kaitai_struct_tests) - all the imporant stuff about testing is described in its README.

**Comment by CarelessChaser** [comment]
Could you, please, add this to DEVELOPERS.md?
Also, I think, we need place for questions and discussions.

**Comment by GreyCat** [comment]
Ahem, it is already in DEVELOPERS.md - https://github.com/kaitai-io/kaitai_struct_compiler/blob/master/DEVELOPERS.md#building-an-universal-package

What place would you prefer? We can start a mailing list, forum or something like that? Would a Google Groups-powered mailing list will do?

**Comment by CarelessChaser** [comment]
I prefer mailing list. BTW, I don't believe Google, because they like to close popular services, such as Google Code, RSS, Buzz, Answers and many others.

Instead, I can recommend you popular service http://www.nabble.com/ where you can start mailing list, forum, blog, etc. Just read about it.

Also, there is http://librelist.com/

**Comment by GreyCat** [comment]
As far as I see (and remember), Nabble does not host mailing lists per se, it just archives externally-hosted mailing lists? Or, alternatively, one can use their forum engine, which has receive-as-email and post-by-email features, but it's pretty unorthodox (for example, to post by e-mail, each user has to request a unique e-mail address like `ml-node+s123456789h15@n4.nabble.com>` and post there).

Librelist seems to be pretty much dead - I haven't found a single active project hosted there. Last status update from 2009 suggests that even if project is working right now, chances of it just vanishing are pretty high.

While I have concerns about Google too, if we're to choose between Google, SF.net and Librelist, probably Google (or Google + Nabble) is the safest and least annoying choice of these 3 (SF.net tends to append tons of ads to every message).

**Comment by LogicAndTrick** [comment]
I've seen some projects using [Gitter](https://gitter.im/), but it doesn't have forum-style topics (it's basically IM) so it would get messy with any significant number of people.

Another option would be just a discussion Github repository where each discussion thread is an issue. That keeps everything in one spot, and Github already has a decent issue/repo email notification system.

**Comment by CarelessChaser** [comment]
Well, let's use Google + Nabble. I don't like Github for discussion because there is no semantic threads, instead we have issues, and we will have many opened issues that will be not issues.

**Comment by GreyCat** [comment]
Here we go: https://groups.google.com/forum/#!forum/kaitai-struct

**Comment by GreyCat** [comment]
And here's Nabble interface to it: http://kaitai-struct.2356954.n4.nabble.com/

**Comment by GreyCat** [comment]
I believe that compilation works now, so I'm closing this issue. Feel free to reopen if something's still unclear.
