### ISSUE TITLE
Broken in 0.8, nullable instance produces missing declaration

### ISSUE THREAD

**Issue by webbnh** [kaitai-io/kaitai_struct_compiler#127]
I'm working on a reproducer; meanwhile, see the lobby chat from [here](https://gitter.im/kaitai_struct/Lobby?at=5a80faf118f388e6268f8c59) to [here](https://gitter.im/kaitai_struct/Lobby?at=5a81946cf283b8e5464f7b80).

**Comment by GreyCat** [comment]
This issue tracker is actually no longer used (see the README note), I've moved it to https://github.com/kaitai-io/kaitai_struct/issues/355
