### ISSUE TITLE
Instances values are missing after JSON.stringify

### ISSUE THREAD

**Issue by ShishkinDmitriy** [kaitai-io/kaitai_struct_compiler#139]
Hello,
I have some troubles with the generated javascript Struct.
When I call `JSON.stringify(...)` then all instances are missing.
But I see them in WebIDE after `export to JSON`.

Best regards, 
Dmitriy

**Comment by GreyCat** [comment]
Ok, so probably WebIDE does *not* use `JSON.stringify`, and uses something else? Why not take a look in WebIDE code if you want similar functionality?

**Comment by GreyCat** [comment]
Ah, moreover, it's an issue in wrong repo.
