### ISSUE TITLE
Permissive License

### ISSUE THREAD

**Issue by sirinath** [kaitai-io/kaitai_struct_compiler#14]
Wondering if you are willing to switch to more permissive licenses like ASL 2.0, MIT, BSD for the Kaitai projects?

**Comment by GreyCat** [comment]
Kaitai Struct runtimes are already licensed as MIT or Apache2. Kaitai Struct compiler is GPLv3. Test suite and documentation licensing are yet to be decided, but probably it should be a combination of CC-BY and MIT.

So, I presume you're asking for change of compiler's license. Why would you want to do it? What's good it for you and what's good in it for us?

**Comment by sirinath** [comment]
There is always a reluctance to use GPL as it might taint the code. If the compiler outputs some of its internal structures in the compilation process then what it generates is also GPL. In case of GNU Compilers there is a special exception for this. 

But any way using GPL is hard as it is not readily whitelisted in companies. Also you have to carefully evaluate it it taints you code, if the project gets abandoned whether you can continue keeping the freedom to relicense under a different license, etc.

**Comment by sirinath** [comment]
Also the if the license is to be change it should be done quickly since you have to get permission from the contributors and you do not have a CLA.

**Comment by GreyCat** [comment]
> There is always a reluctance to use GPL as it might taint the code.

I don't see "always a reluctance to use GPL" anywhere. Myriads of companies, that produce both open source and closed source software, use GNU-licensed software.

> If the compiler outputs some of its internal structures in the compilation process then what it generates is also GPL.

That is doubtable, to say at least, and as far as I know, there have been a court decision on this matter.

> In case of GNU Compilers there is a special exception for this.

There's no "special exception" in GNU *compilers* license. If you mean this one:

```
This GCC Runtime Library Exception ("Exception") is an additional
permission under section 7 of the GNU General Public License, version
3 ("GPLv3"). It applies to a given file (the "Runtime Library") that
bears a notice placed by the copyright holder of the file stating that
the file is governed by GPLv3 along with this Exception.
```

... then it's not a license of *compiler*, but a license of runtime library (libstdc++) it uses and may embed into the executable. It's exactly why we have our runtime libraries in separate repositories and distincly licensed as MIT/Apache2. If you mean [this one](https://www.gnu.org/licenses/gpl-faq.en.html#CanIUseGPLToolsForNF), then it's a question in FAQ, not an exception, or any additional legalese.

There is actually similar text stated in our licensing documentation:

> Note that it applies only to compiler itself, not .ksy input files that one supplies in normal process of compilation, nor to compiler's output files — that consitutes normal usage process and you obviously keep copyright to both.

> But any way using GPL is hard as it is not readily whitelisted in companies. 

I believe that I won't want to support companies that find GPL "hard to use".

> if the project gets abandoned whether you can continue keeping the freedom to relicense under a different license, etc.

You can't, that's the point. You can't just state that "project is abandoned" and close the source.

> you do not have a CLA.

Personally, I generally agree with [people who state that CLAs do more harm than good](http://lanyrd.com/2011/oscon/sgcfd/). As for "good" — it's been shown that CLAs do not work in many countries (due to being untranslated, due to local laws explicitly forbidding waiving of copyrights, etc) and it kind of undermines the whole idea. As for "harm" - for a project of this scale, it would complicate contributions to the point of turning down all potential contributors.

**Comment by sirinath** [comment]
ASL 2.0, MIT, BSD are viewed as business friendly. Also you cannot embed the compiler if it is or use a subset of if it is GPL. When doing outsourcing work the clients also impose what licenses of 3rd party libraries that can be used.

**Comment by GreyCat** [comment]
I reckon that you routinely visit GPL projects and advocate for license switch without any clear motivation  ([backtrader](https://github.com/mementum/backtrader/issues/122), [Quantler Core](https://github.com/Quantler/Core/issues/2), [eris](https://github.com/eris-ltd/eris-cli/issues/855), [gapt](https://github.com/gapt/gapt/issues/560), [HPAC Tensor Transpose Compiler](https://github.com/HPAC/TTC/issues/7), [eventql](https://github.com/eventql/eventql/issues/175), [MonoGame](https://github.com/MonoGame/MonoGame/issues/5031), etc, the list is long).

Almost every project's maintainer asks for why exactly would you want that, and almost universally you answer with standard "business doesn't like GPL" routine. Projects seems to be picked almost randomly, I never seen any signs of personal interest in them.

> you cannot embed the compiler if it is or use a subset of if it is GPL

You can distribute it verbatim and call it as a separate application.

> When doing outsourcing work the clients also impose what licenses of 3rd party libraries that can be used.

I'm sorry, but that's problems of these "clients", not ours.

**Comment by sirinath** [comment]
The projects you we have made the request is because we prefer to use non GPL sourced. This is not directly relevant for your to make a decision for this project as you have to see the merits of using another license vs this.

> never seen any signs of personal interest in them

I do not see how you can make this conclusion. We are in automating quant trading. Backtrader, Quantler Core are related. Also since blockchain technology is very topical in finance now we were evaluating some of the existing projects in this space. Also quotes are event data. Also game frameworks can be used for Linear Algebra and Visualisation. Having said this we do not end up using each project we have a look at.

Anyway licensing decision is yours. Was just asking to see if there was a possibility. Our interest in this project was to see if this approach to generating FIX protocol engine would results in a more efficient version than some of hand tuned open source versions. Also we try to keep software we depend on free from *GPL as much as possible.

**Comment by GreyCat** [comment]
There is always a possibility — but so far you haven't provided any rationale on why should we switch, besides "we prefer to use non GPL sourced" and "we try to keep software we depend on free from *GPL". If you do have any specific problems, we can discuss it — but you haven't named any.

You don't list any benefits that Kaitai Struct will get either. So far it looks like you're asking for something serious (that might harm the project) for your benefit, and, eventually, you're might not even "end up using each project we have a look at". It doesn't work that way.

**Comment by sirinath** [comment]
Our conclusion is GPL / copyleft licenses are not conducive to our business as in many client owns the code from what we build for them and the clients should be free to license what we deliver as he wishes with us also retaining the right to reuse in other projects in some cases. This is case for many small scale outsourced / contract bespoke development projects. Negotiating to use copyleft components unless absolutely necessary reduces the simplicity and swiftness to finalise contract. Sometimes you have to get approval for each component in the solution for such licenses which is time consuming and a overhead especially for small companies. This is our main reason (purely from our perspective) would be the same for many other small time companies in the same space. License change will help such companies also. We do not have any other rationale than this.

>  "end up using each project we have a look at". It doesn't work that way.

If we do not get a project in the space or if X technology is part of the solution there is no way to use it? But also we have to be aware what we can use if we get any projects that can benefit the relevant technology provided it has conducive license if we get a project that can benefit from Y. I do not know how this does not work that way.

Any way this conversation not going productively. This is your software hence upto you to decide how it is licensed. I just made a request to see if you will to change it. If you do it can benefit us and other similar companies.

**Comment by sirinath** [comment]
Also though there is many reasoning towards copyleft, unless business model is GPL + CLA + Commercial there is benefit for using a copyleft license. Also there are many companies which are very successful being 100% open source + permissive also: http://wso2.com/.

**Comment by GreyCat** [comment]
Given the provided arguments, I see no point in raising a discussion to change license. This could potentially harm the project, and I don't see why we should help your business needs for free.
