### ISSUE TITLE
Desire to add "offset" language to ksy structure

### ISSUE THREAD

**Issue by dhushon** [kaitai-io/kaitai_struct_compiler#143]
Looking to parse "block" based binary structures...
in these structures you might have fixed length blocks that have variable completion so the ksy might want to "read"/"write" the first say 256 bytes in a 1k block, and then skip(read) or pad(write) to the end of the block boundary.

Thoughts?

**Comment by GreyCat** [comment]
First of all, let's move it to main repository. Please read this repo's README.

**Comment by KOLANICH** [comment]
Is it possible to just disable this bug tracker?

**Comment by GreyCat** [comment]
It is, but first we need to deal with remaining several bugs in it, so we won't lose them.
