### ISSUE TITLE
Running mach_o.ksy with target Golang does nothing

### ISSUE THREAD

**Issue by blacktop** [kaitai-io/kaitai_struct_compiler#144]
outputs:

```bash
EnumType(List(magic_type),IntMultiType(false,Width4,Some(BigEndian))) (of class io.kaitai.struct.datatype.DataType$EnumType)
```

**Comment by blacktop** [comment]
Whoops just saw #146, although it is kind of weird that you have it enabled at all in 0.8 if it isn't ready yet?

**Comment by GreyCat** [comment]
Golang target currently passes ~41% of tests, and that's enough for simpler format specs, and it looks like general interest towards it is not very high.

Also, please don't use this tracker, as per [README in this repository](https://github.com/kaitai-io/kaitai_struct_compiler/blob/master/README.md#submitting-bugs--issues--ideas).

 If you're interested, I suggest to continue this discussion either in https://github.com/kaitai-io/kaitai_struct/issues/146 or in the new issue in https://github.com/kaitai-io/kaitai_struct/ repo.
