### ISSUE TITLE
CSharpCompiler.scala | attrFixedContentsParse may generate invalid code

### ISSUE THREAD

**Issue by titobrasolin** [kaitai-io/kaitai_struct_compiler#21]
In C# the byte number type is unsigned, that's why the generated code for this simpe ksy is invalid:

    meta:
      id: test
    seq:
      - id: something
        contents: [0xFF]

Generated code:

    private void _parse()
    {
        _something = m_io.EnsureFixedContents(1, new byte[] { -1 });
    }

Of course -1 cannot be converted to byte.

**Comment by GreyCat** [comment]
Thanks! Actually, there are already tests for it, but `attrFixedContentsParse` wasn't using ready-made byte array translator methods. I'll try to fix it right away.

**Comment by GreyCat** [comment]
Ok, here you go: https://github.com/kaitai-io/kaitai_struct_compiler/commit/f2cadcf5f2d102d646d050d535dafa243c982eda

It went to the CI, so builds should be available in 5-10 minutes.

If you're using Windows, you can get ready-made .msi for installation from https://ci.appveyor.com/project/GreyCat/kaitai-struct/build/1.0.132/artifacts

**Comment by titobrasolin** [comment]
Problem solved, thanks a lot GreyCat!
