### ISSUE TITLE
Error message should show .ksy line number

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct_compiler#22]
To make debugging easier the compiler should show the line number of the erroneous part of the .ksy file if it is available.

This also means that we have to use such YAML readers which are able to store this information.

We also have to solve the mapping between the different data representations: for example if the compiler uses object model (not YAML .ksy) as input and we throw an exception when we see that the `meta.endian` property in the object model is not `be` or `le`, then one of the options is to store that `meta.endian` was the errorneous property and then we have to map `meta.endian` in the YAML parser to the specific line (if YAML was the input). Other option is to store YAML position in the property metadata in a parser-independent way.

Also we should make more descriptive error messages, I got the following error when I tried to compile png.ksy to javascript: `java.lang.RuntimeException: Unable to parse fixed content: null`. The problem is that the context is lost. I have no idea where is a null in the object model.

**Comment by GreyCat** [comment]
Code introduced in https://github.com/kaitai-io/kaitai_struct/issues/42 partially solves this problem, by offering path in object tree to find the source of the parsing error. Examples:

```
/seq/1/blah: unknown key found, expected: contents, doc, encoding, id, if, process, repeat, repeat-expr, repeat-until, size, size-eos, type
/meta/endian: must be `be` or `le`, but `Some(bad)` found
/meta/foo: unknown key found, expected: application, endian, file-extension, id
/meta/id: expected string, got None (class scala.None$)
/meta: expected map, got 123 (class java.lang.Integer)
/seq: expected array, found foo
```

**Comment by koczkatamas** [comment]
Wow, super nice!

I will try to check this out tonight and implement soon in the Web IDE too.

**Comment by GreyCat** [comment]
I believe that this issue is solved to some degree. Actually, to move forward in this area, we'd need a better YAML parser. I've just created as issue for that: https://github.com/kaitai-io/kaitai_struct/issues/229

So, I'm closing this one and propose to move all further error-message parsing related discussions there.
