### ISSUE TITLE
CTOR mismatch in Java in case of types in different files.

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#29]
I want to use types in different files, pretty much like you suggest in [some other issue comment](https://github.com/kaitai-io/kaitai_struct/issues/48#issuecomment-261751957) and are using for the [network examples](https://github.com/kaitai-io/kaitai_struct_formats/tree/master/network). The problem I have is that my generated code doesn't compile in Java and that's the same with your network examples: I was compiling ethernet_frame with its dependencies and have the same result, that the generated code is invalid.

Have a look at some CTORs:

    public EthernetFrame(KaitaiStream _io, KaitaiStruct _parent, EthernetFrame _root) throws IOException {
        super(_io);
        this._parent = _parent;
        this._root = _root;
        _read();
    }

    public Ipv4Packet(KaitaiStream _io, KaitaiStruct _parent, Ipv4Packet _root) throws IOException {
        super(_io);
        this._parent = _parent;
        this._root = _root;
        _read();
    }

And how those are called:

    this.ipv4Body = new Ipv4Packet(_io__raw_ipv4Body, this, _root);

All CTORs including a `_root` seem to have themselfs as type for the root, which make sense if the ksy files are self contained, but seems to break in a parent/child relation ship. In such a case the root would need to be either a constant root type or it would need to be same type like parent or maybe some constant/parent-like root and additionally some child specific root?

Or am I doing something wrong?

I'm using the current master of the compiler.

**Comment by GreyCat** [comment]
This is indeed a bug, thanks for reporting that. As far as I can see, one obvious solution is to stop supplying  our `_root` as `_root` (and, of course, parent as well) for all the classes that are not declared in current file.

**Comment by tschoening** [comment]
With that approach one couldn't access the entire `EthernetFrame` from within `Ipv4Packet` anymore, right?

Don't you know already about the parent-child-relationship in `Ipv4Packet` and could simply add one CTOR with a root of type `EthernetFrame`? In effect you would introduce two roots, one local to the file with the type of the file and one global belonging to the parent of the file, if any. Something like the following:

    public Ipv4Packet(KaitaiStream _io, KaitaiStruct _parent, Ipv4Packet _self|localRoot) throws IOException {


    public Ipv4Packet(KaitaiStream _io, KaitaiStruct _parent, EthernetFrame _[parent|global]root) throws IOException {

This way all currently generated invocations of CTORs would simply start working. One interesting question would be what `_root` should resolve to in which case. I would have expected that `_root` would be `EthernetFrame` in any case and `_parent` might be `EthernetFrame` as well, but not necessarily, depending on the context.

**Comment by GreyCat** [comment]
> With that approach one couldn't access the entire `EthernetFrame` from within `Ipv4Packet` anymore, right?

You can't access it right now anyway. Besides, if we're talking about network packets hierarchy, if we're working on layer X, accessing anything on layer X - 1 is pretty much pointless, as there could be anything there, there are no guarantees that `Ipv4Packet` will be embedded in `EthernetFrame` and not like X.25, token ring, or anything like that. And `_root`, if used, should be always point to "local root", or else we'll need to invent some rules for resolving that.

> Don't you know already about the parent-child-relationship in Ipv4Packet and could simply add one CTOR with a root of type EthernetFrame?

Actually, no. Right now every file is compiled independently. If we encounter a reference to undefined type, we just treat it as "opaque" type, i.e. "some user-defined type that we don't know anything about".

**Comment by GreyCat** [comment]
Here you go: I've added [new test "opaque_external_type"](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/opaque_external_type.ksy) that addresses this issue, and applied some fixes. You can track the progress for this test [on our CI](http://kaitai.io/ci) - so far, Ruby, C#, Java and PHP has it working. There are some problems with C++ and Python, though: we'll need to either declare the class or import proper declaring file manually.

**Comment by tschoening** [comment]
Guten Tag Mikhail Yakshin,
am Dienstag, 22. November 2016 um 14:02 schrieben Sie:

> Here you go:[...]

The code compiles now, thanks. Because of your last sentence about
"some problems", I'll leave closing the issue to you again.

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Comment by GreyCat** [comment]
Got everything up, except for JavaScript. The problem with JavaScript is that we need to import opaque classes somehow, and I guess it's very untrivial, given the lack of standard. @koczkatamas, any ideas? How do we make a code like that work?

```javascript
var OpaqueExternalType = (function() {
  function OpaqueExternalType(_io, _parent, _root) {
    this._io = _io;
    this._parent = _parent;
    this._root = _root || this;

    this.one = new TermStrz(this._io, this, this._root);
    // ^^^ this one obviously fails due to TermStrz not being defined
  }

  return OpaqueExternalType;
})();
```

**Comment by tschoening** [comment]
Sorry, but I still have a question on this one:

> As far as I can see, one obvious solution is to stop supplying our _root as _root (and, of course, parent as well) for all the classes that are not declared in current file.

If understand the problem correctly, it was not within your compiler creating Java itself, but only with the resulting Java, because of different types for `_root`, because of types defined in different KSY files, things you don't know about during the compilation process because all files are compiled individually...

But if the problem only was with `_root`, why did you change the CTOR calls to not provide `this` anymore as well? `_parent` was of type `KaitaiStruct` already, so no type problems in Java, and providing `this` as parent seems to make sense to me. Even if you argue with the network example that some layer shouldn't check things in lower layers, one might not have such a strict relation ship and implement some other meaning of `parent`.

In the end, couldn't even `_root` have been handled like `_parent`, simply of type `KaitaiStruct` and always forwarded through the instances? That's how I understood your code in the first place: `_parent` is the higher level container for any reason, `_root` is the highest level container for any reason. If both are `KaitaiStruct` in the CTORs of all classes, this would have worked easily. And that was only the problem, that `_root` was not `KaitaiStruct`. This generic type isn't even a problem, because it can easily be casted by the Java user.

Currently `_ parent` and `_root` properties don't make sense in Java as they all provide the current instance and not what the names imply. While in your original code a caller got some other instance. I just think of some higher level parser using your generated Java parser classes and for that higher level parser accessing some kind of `_parent` might have been useful.

https://github.com/kaitai-io/kaitai_struct_compiler/commit/93c223a36db7d44f49bed8ea3b6cf3bbfef10448#diff-fc2acab10340febf58569b1517b3d4b5R304

**Comment by tschoening** [comment]
OK, I think you can forget most of this... `_parent` and `_root` are designed to be locally per file/compilation unit and `_ parent` more or less only worked by accident, because `KaitaiStruct` was used as type somehow.

So let me ask differently:

Couldn't that be an easy feature to get if it already worked with in my case with only removing `_root` from the CTOR invocation?

**Comment by GreyCat** [comment]
> This generic type isn't even a problem, because it can easily be casted by the Java user.

Actually, it *is* a problem. We don't just have to care about manual actions of Java user, but we'll have to handle expressions like `_root.header.some_field`. Right now they compile straightforwadly to `_root().header().someField()` - and that works essentially because `_root` is of proper type, not just `KaitaiStruct`.

> `_parent` and `_root` are designed to be locally per file/compilation unit and `_parent` more or less only worked by accident, because KaitaiStruct was used as type somehow.

Yes, kind of like that. Both `_parent` and `_root` require some amount of type derivation, that just doesn't exist between different files (as they are compiled separately and compiler doesn't know anything about other types and can't derive any relationships between them).

It is possible to do cross-file versions of `_parent` and `_root`, but that's generally whole other story. You were absolutely correct when you've pointed out that there should be two distinct implementations - i.e. "global" `_root` / `_parent` and a "local" one. And to do the "global" implementation, we'll have do to proper multi-file compilation. That would probably require some "project" file, to designate which of the added .ksy files should be considered "global root", and which are connected to it, or some sort of "import" / "include" functionality, etc.

To be honest, right now I don't think it's feasible to do that. That would be overly complex solution, we'll spend lots of time doing it, and chances are that ultimately you won't like the result.

**Comment by GreyCat** [comment]
Finally, `opaque_external_type` works for everything, so I guess it's time to close the bug.
