### ISSUE TITLE
FixedContents signedness issue C++

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct_compiler#30]
Look at the image below to see the issue:

![image](https://cloud.githubusercontent.com/assets/2608082/20502351/f49db0d2-b03d-11e6-9cda-f1ee7b03892f.png)

This can be a bug in Scala.js as this code runs differently: `"%x".format(192.toByte)`
 - in Scala it prints out `c0` while
 - in Scala.js it prints out `ffffffc0`

**Comment by koczkatamas** [comment]
Looks like it's by design: https://github.com/scala-js/scala-js/issues/2206

**Comment by GreyCat** [comment]
Good point, thanks for the research. Looks like we should really set up Scala.js tests in CI to check that the result of compilation is the same for JVM & JS versions...

**Comment by GreyCat** [comment]
Should be fixed now. Reworked lots of `ensureFixedContents` API in process - it now strives as much as possible to use standard byte array implementations and consistent `doByteArrayLiteral` in language's translator. Updated http://kaitai.io/repl as well. Please check it out.

**Comment by rnz** [comment]
Why generated cpp have `ensure_fixed_contents` with two arguments but kaitaistream.h  have `[std::string ensure_fixed_contents(std::string expected);` with one argument?

**Comment by GreyCat** [comment]
This is a change between 0.5 and (upcoming) 0.6. Probably you have compiled cpp with 0.5 compiler and have kaitaistream.h from 0.6 runtime.

**Comment by rnz** [comment]
I think you need version tags in repository https://github.com/kaitai-io/kaitai_struct_perl_runtime

**Comment by GreyCat** [comment]
Good idea, thanks.

**Comment by GreyCat** [comment]
@rnz Here you go, tag for 0.5 is added. As far as I remember, 0.5 was the first release with Perl support.

**Comment by rnz** [comment]
Sorry, I talk about cpp runtime - and currently I see - tags 0.5, 0.4 in it repos

**Comment by rnz** [comment]
Thank You Man! ))

**Comment by GreyCat** [comment]
Note that 0.5 will have this bug with Scala.JS output. It's only fixed in current git.

**Comment by GreyCat** [comment]
/ping @koczkatamas — can you check that it's all right and close this one, if it works for you?

**Comment by koczkatamas** [comment]
It works, thanks!
