### ISSUE TITLE
Possible issue with accessing enums in "child" types in Java.

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#34]
I have different types for different parts of my data and two of those types use `enums`, the main type represented by the KSY file itself and some user specific type within that file. The main type needs to check some fields which are represented by a child type and this compiles fine and works in your Ruby visualizer, but doesn't compile in Java.

Please have a look at the following, heavily reduced KSY, the problem is with `is_var_data_blocks_decrypted`:

    meta:
      id:      fmts_oms_apl_payload
      endian:  le
    
    seq:
    [...]
    
    instances:
    [...]
      is_var_data_blocks_decrypted:
        value:  is_header_none or
                (
                  is_header_short and
                  (
                    (header_short.config_field.enc_mode         == enc_mode::none) or
                    (
                        (header_short.config_field.enc_mode     == enc_mode::aes_cbc_iv_non_zero) and
                        (header_short.config_field.aes_byte_cnt == 0)
                    )
                  )
                )
    [...]
    
    enums:
      header_type:
      [...]
    
    types:
      fmts_oms_apl_header_config_field:
        seq:
          - id:   lsb
            type: u1
          - id:   msb
            type: u1
    
        instances:
        [...]
    
        enums:
          enc_mode:
            0x00: none
            [...]
    [...]

As you can see, `enc_mode` comes form the child type `fmts_oms_apl_header_config_field`. The generated Java code is the following:

    public Boolean isVarDataBlocksDecrypted() throws IOException {
        if (this.isVarDataBlocksDecrypted != null)
            return this.isVarDataBlocksDecrypted;
        boolean _tmp = (boolean) (isHeaderNone() || isHeaderShort() && headerShort().configField().encMode() == EncMode.NONE || headerShort().configField().encMode() == EncMode.AES_CBC_IV_NON_ZERO && headerShort().configField().aesByteCnt() == 0);
        this.isVarDataBlocksDecrypted = _tmp;
        return this.isVarDataBlocksDecrypted;
    }

The enum is not accessed by it's type, but assumed to be in the same package like where it's used and that doesn't compile.

The problem is that I'm unable to find some syntax on how to provide the proper child type in the KSY already. If I try e.g. the following, I get an compilation error:

    header_short.config_field.enc_mode       == fmts_oms_apl_header_config_field.enc_mode::none
    header_short.config_field.enc_mode       == fmts_oms_apl_header_config_field::enc_mode::none

All the examples in your formats etc. only use `enums` in the same level like where those are declared. But as it works in Ruby, am I doing something wrong or is this just coincidence and shouldn't be allowed in all languages?

Would be great if Java could support it, it's simply cleaner to model the types the way I have them currently.

**Comment by GreyCat** [comment]
KS currently aims to follow the same semantics as Java and C++ use: if you reference a name (type name or enum name), first of all, it tries to find it in current namespace (i.e. defined inside current type), then it tries outer namespaces (i.e. travelling up the hierarchy of nested classes), until it will find what's needed. If it does not find a type or enum, it will assume that it's a top-level entity defined in some other file.

Unfortunately, there is currently no way to specify "proper" namespacing, either absolute or relative for either types or enums. What's even worse, "types" are indeed properly resolved by KS itself, but "enums" are not: they are just thrown as is (as strings) into the target language file, hoping that target language will sort them out. Unfortunately, it's doesn't work as intended on some languages (namely, Python, PHP and, to some extent, JavaScript). This is a known problem that, unfortunately, requires quite large investment of effort to fix, but I hope to get to it soon.

The easy answer is to either move `enc_mode` into your `fmts_oms_apl_payload` type (and use it everywhere), or use it only where it is defined — i.e. define that instance `is_var_data_blocks_decrypted` (or at least parts of it that need to reference enum) inside `fmts_oms_apl_header_config_field`.

If you want some syntax to specify stuff in other types then, probably, we should make a separate discussion for that and decide on that syntax. Actually, we've never ever brought a concept of "type name" to the expression language, and that by itself would require some careful thinking over.

**Comment by tschoening** [comment]
Guten Tag Mikhail Yakshin,
am Donnerstag, 24. November 2016 um 23:41 schrieben Sie:

> What's even worse, "types" are indeed properly resolved by KS
> itself, but "enums" are not: they are just thrown as is (as strings)
> into the target language file, hoping that target language will sort
> them out.

That's not necessarily a wrong approach, because if you would simply
forward a statement like the following as string to the target
language, that would solve the problem in Java:

> fmts_oms_apl_header_config_field.enc_mode::none

Of course that might not work in other languages, so I understand why
you are not doing it. OTOH, what currently works in Ruby doesn't in
Java, so a Ruby KSY-author wouldn't even have recognized this and a
Java focused author might not care about Ruby. Difficult... :-)

> i.e. define that instance `is_var_data_blocks_decrypted` (or at
> least parts of it that need to reference enum) inside
> `fmts_oms_apl_header_config_field`.

That's what I had in mind as well already and I think it's even the
overall cleaner approach to do so, because such an instance would be
visible again in Visualizer an ease debugging and such.

How about just adding your explanation with an example and the
benefits of using an enum-local instance for debugging as "workaround"
or simply a link to this "issue" to the docs? Sounds like the easiest
solution.

And while I'm at it:

This question is more a usage one than an issue, but I didn't know
where to ask it elsewhere as not an issue. So is it OK if I ask such
things as an issue or is there some better way? IMHO every publicly
available question on search engines might be of help to someone, call
it "issue" or not.

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Comment by GreyCat** [comment]
> OTOH, what currently works in Ruby doesn't in Java

Ruby is somewhat special in aspect of enums: it uses symbols instead of enums, thus it does absolutely no checks. So it's more like using strings that anything else.

> How about just adding your explanation with an example and the
benefits of using an enum-local instance for debugging as "workaround"
or simply a link to this "issue" to the docs? Sounds like the easiest
solution.

I'm currently working on "new" user guide: https://github.com/kaitai-io/kaitai_struct_doc/blob/master/user_guide.adoc

That's a good point, I'll try to document these questions / issues there.

> This question is more a usage one than an issue, but I didn't know
where to ask it elsewhere as not an issue. So is it OK if I ask such
things as an issue or is there some better way? IMHO every publicly
available question on search engines might be of help to someone, call
it "issue" or not.

I have absolutely no problems with communicating using GitHub issues. We can just mark them as "question" and that's ok.

Alternatively, you can join our [chat at gitter](https://gitter.im/kaitai_struct/Lobby) - probably more people would may answer there and do so in a quicker, more interactive manner, or you might submit [questions at StackOverflow](http://stackoverflow.com/questions/tagged/kaitai-struct) - that's also good for the sake of making answers stand out more.

**Comment by tschoening** [comment]
Thanks for those hints.
