### ISSUE TITLE
Need help for lookahead check to distinguish two types.

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#35]
I have the following simplified structure:

> Block1: [[Header 1.1][Header 1.2][Payload 1]]
> Block1: [[Header 2.1][Header 2.2][Payload 2]]
> Block1: [...]
> Block2: [[Header 3][Payload 3]]

Block1 and 2 are different types and I can parse Block1 successfully already. Block2 is optional and I only know about if it is present or not if I parse the first byte after Block1 and that byte tells me that it's Block2.

I don't know how to describe that I want to look one byte ahead without necessarily consuming that byte and depending on that byte I either want to parse Block1 or ABORT, because Block2 is parsed in a different type already. My wanted behaviour is so that I parse Block1 as long as I have Block1 and Block2 simply tests if it is at the end of the stream and if so, it is ignored, else it is parsed, because it only can be at the end of the stream, and can only occur once.

Additionally, I can't easily share headers or such in one common type, because in case of Block1 the header contains additional information I need to check within Block1 to know how to proceed, while the same header of Block2 only contains the information that it is Block2, without any further information. If I use some common type for both blocks for the header, I would need to put additional logic not related to Block2 into that type and I would like to avoid that.

Is something like that possible? What I would need is to be able to read some byte in `repeat-until` on a specified position and check that value. But I can't use and instance, because that would only be evaluated once.

This is how I use my types:

Some container:

    - id:   vdbs_decrypted_wo_aes_verify
      type: fmts_oms_apl_vdbs_decrypted
      if:   are_vdbs_decrypted_wo_aes_verify
    - id:   vdbs_decrypted_with_aes_verify
      type: fmts_oms_apl_vdbs_decrypted_with_aes_verify
      if:   are_vdbs_decrypted_with_aes_verify
    - id:   vdbs_encrypted
      size: header_short.config_field.aes_byte_cnt
      if:   are_vdbs_encrypted
    - id:   opt_prod_spec_data
      type: fmts_oms_apl_opt_prod_spec_data
      if:   not _io.eof

Unless encrypted, all the vdbs-stuff resolves to the following:

    seq:
      - id:     data_block
        type:   fmts_oms_apl_vdb
        if:     not opt_prod_spec_data_found
        repeat: eos
        # TODO recognize opt_prod_spec_data?
    
    types:
      fmts_oms_apl_vdb:
        seq:
          - id:   header
            type: fmts_oms_apl_vdb_header
          - id:   data
            size: header.data_size

**Comment by tschoening** [comment]
Note to self: In theory lookahead can be implemented on Block1-level using instances, Block1 simply needs to check if there's another byte of data and which value it has. Something like the following, which isn't working yet, there's still some attempt to read a byte to many:

    seq:
      - id:     var_data_block
        type:   fmts_oms_apl_vdb
        repeat:       until
        repeat-until: _.next_is_prod_spec_data
    [...]
        instances:
          read_next_byte_if:
            pos:  _io.pos + 1
            type: u1
            if:   not _io.eof
          next_is_prod_spec_data:
            # Auto-unboxing of "null" in Java leads to a NullPointerException at runtime.
            value:  #not _io.eof                   and
                    (
                      (read_next_byte_if == 0x0F) or
                      (read_next_byte_if == 0x1F)
                    )

**Comment by GreyCat** [comment]
Generally, looking ahead is not what Kaitai Struct encourages. It means reinterpreting, rollbacks, etc, and that doesn't really play good with binary formats, so we usually try to avoid it.

In your case, I believe the solution would be simple: let's separate first byte from both Block1 and Block2 and do the following structure:

```yaml
seq:
  - id: marker_byte
    type: u1
  - id: block
    type:
      switch-on: marker_byte
      cases:
        0x0f: block2_without_first_byte
        0x1f: block2_without_first_byte
        _: block1_without_first_byte
```

then this structure can be repeated as many times as you need it — up to the end of stream, until some data encountered, a fixed number of times, etc, etc.

If you need to access that first byte from `block1_without_first_byte`, it's pretty easy to do using:

```yaml
types:
  block1_without_first_byte:
    seq:
      # ...
    instances:
      first_byte:
        value: _parent.marker_byte
```

Would that work, or am I missing something vital here?

**Comment by tschoening** [comment]
That would work, I just didn't like that approach from a design point of view... But I didn't think of simply doubling the `marker_byte` using an instance to get my "self containing" type AND looking at my spec again, I even have a good name now for a type implementing only the check of the `marker_byte`. Thanks for the idea!

**Comment by GreyCat** [comment]
Well, that's true that Kaitai Struct kind of shifts the traditional parsing paradigms.

For example, when most parsers distinguish "headers" and "body", KS usually doesn't have to. But if you'll think of it rationally, that paradigm - i.e. "headers" + "body" - is actually born because of C-style parsing, when you had to have different structures for fixed part of the data and variable-length data. In many cases, there's just no need to add these extra artificial subobjects in KS. 

Another example is a concept of "block". It actually comes from the ENBF-style grammar specifications, when people use backtracking liberally just for because they like it that way. They say that at this particular place of stream one can have "block1" or "block2", but to actually distinguish them you'll have to read first X bytes and only then you can make decision. From Kaitai Struct's point of view, this is wrong: if these "blocks" actually have some common part that is used later to distinguish how to parse the rest of it, then these "blocks" are not atomic entities, but instead consists of at least 2 parts, i.e:

* block1 = distinguishing_header + block1_body
* block2 = distinguishing_header + block2_body

... and if you'll think of it that way, there is actually no point in having block1 and block2 per se. They're just 3 types here: distinguishing_header, block1_body, block2_body, not 5.

**Comment by tschoening** [comment]
I guess this would ultimately lead to a discussion about taste and such, because in my concrete example the `distinguishing_header` is mainly part of `block1` and 99% of the cases or the value it provides is used for `block1`. There's only one exception and that is the indication that no `block1` is present, but a `block2`, which looks more like a workaround in the spec already to me to support this use case.

So to me it simply feels more natural to design this header being part of `block1` and handle the exception as such. Additionally, I try to keep my resulting public API of the generated parser in mind: Using your `switch-on` I'll loose publicly documented type information and need to check the type on runtime and such, while with the look ahead approach it's absolutely clear on what you access.

Being able to choose is not so easy sometimes... :-)
