### ISSUE TITLE
Is there some way to access the last element of an array?

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#40]
I have the following KSY:

      - id:           vif_exts
        type:         fmt_oms_apl_vdb_header_vib_vife
        if:           vif.has_vife
        repeat:       until
        repeat-until: not _.has_vife

Is there some way to access the last element of the array of read elements? I tried specifying `-1` but at least with Java this is 1:1 forwarded to `get` and fails, because `-1` is no valid index.

I need to decide later in the stream according to the last element read of the provided type what to do with some bytes. The only workaround I currently have is to read that byte again, because my reading order allows to know the index of that byte.

**Comment by GreyCat** [comment]
I believe that `vif_exts.last` should do what you want.

**Comment by tschoening** [comment]
Thanks, that works and makes implementation much easier. Out of interest, are you even supporting `last - 1` or such? Because in Java your `last` got translated to 

> switch (_parent().dummy().get(_parent().dummy().size() - 1)) {

while in Ruby it seems you are simply using some `last` method of the underlying data structure. I've tested

> switch-on: _parent.dummy.(last - 1)

and 

> switch-on: _parent.dummy.last - 1

and the first failed to compile and the second hadn't any influence on the read index, like expected.

**Comment by GreyCat** [comment]
`.last` is just a method of array that was easy (and useful) to implement, as the majority of array implementations in target languages have it one way or another (or at least it's easy to emulate). Here's the current translation spec:

```scala
    full("a.last", ArrayType(CalcIntType), CalcIntType, Map[LanguageCompilerStatic, String](
      CppCompiler -> "a()->back()",
      CSharpCompiler -> "A[A.Length - 1]",
      JavaCompiler -> "a().get(a().size() - 1)",
      JavaScriptCompiler -> "this.a[this.a.length - 1]",
      PythonCompiler -> "self.a[-1]",
      RubyCompiler -> "a.last"
    )),
```

In PHP, that would be probably `end(a)`. In Perl, `$a[-1]` or something like that. Actually, having negative indexes support would be a cool idea, but it would have required lots of ugly runtime code for languages that don't support them.

**Comment by tschoening** [comment]
Guten Tag Mikhail Yakshin,
am Donnerstag, 8. Dezember 2016 um 09:28 schrieben Sie:

> Actually, having negative indexes support would be a cool
> idea, but it would have required lots of ugly runtime code for
> languages that don't support them.

And currently nobody seems to miss that feature, so no problem at all.

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow
