### ISSUE TITLE
Make binary literals more readable?

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#41]
For various reasons I have the following, which I would like to get more readable. This is two bytes now, but I find myself to be using 0b literals a lot and even those for 1 byte are a bit hard to read IMHO.

    unit_and_multiplier_type_vife:
      0b0000000000000000: orthogonal_start
      0b0001111000000000: orthogonal_compact_prof_with_regs
      0b0000000011111011: linear_ext_1_start
      0b0000000011111101: linear_ext_2_start
      0b0001011111111101: linear_ext_2_error_flags
      0b0001100011111101: linear_ext_2_error_mask

I would prefer something like the following if possible, 4 bits boundary would even be better:

    unit_and_multiplier_type_vife:
      0b00000000_00000000: orthogonal_start
      0b00011110_00000000: orthogonal_compact_prof_with_regs
      0b00000000_11111011: linear_ext_1_start
      0b00000000_11111101: linear_ext_2_start
      0b00010111_11111101: linear_ext_2_error_flags
      0b00011000_11111101: linear_ext_2_error_mask

Not that important of course, just a suggestion.

**Comment by GreyCat** [comment]
Good idea, thanks! Probably should be fairly easy to implement.

**Comment by koczkatamas** [comment]
After a quick Google search it looks like you can put underscore into numeric literals almost anywhere in Python 3.6, C# 7, Java 7 (maybe others), not just group them at every 4, 8, etc. bits.

So I think we can do that too.

Other interesting question: should we preserve where were the underscores and generate them into the same place for languages which support underscores in numeric literals? 
(I think it would be more work than the benefits it would gave, especially we support older versions of languages above, but who knows.)

**Comment by tschoening** [comment]
Guten Tag Tamás Koczka,
am Freitag, 9. Dezember 2016 um 09:52 schrieben Sie:

> Other interesting question: should we preserve where were the
> underscores and generate them into the same place for languages
> which support underscores in numeric literals?
> (I think it would be more work than the benefits it would gave,
> especially we support older versions of languages above, but who knows.)

Agreed, it might make debugging the generated runtime code in case of
errors a tiny bit easier, but I don't think it's worth the work, too.

Doesn't the generated code only contain decimal integers anyway? So
you wouldn't be able to map "_" in binary or HEX literals at all. And
using those two surely is the main use case for such literals. At
least it's in my work currently.

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Comment by GreyCat** [comment]
Right now we don't save the exact form of number literals in generated code. It's not terribly hard to do, but it will involve lots of digging through which languages support which forms of literals (for example, not every language has octal literals) — so, I agree that it's probably not worth the effort, or at the very least, it's a pretty low-priority task.

We might want to keep it written down somewhere, though ;) It might be a good excerise for someone who'd want to join the team and start with something simple and useful :)

**Comment by GreyCat** [comment]
Your wish is granted ;) Should work with dec / oct / hex / bin literals.

**Comment by tschoening** [comment]
Thanks a lot, it's much more readable now.
