### ISSUE TITLE
Enhancements to make overriding types easier?

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#42]
Consider the following generated example of code:

    private void _read() throws IOException {
        this.header = this._io.readU1();
        this._raw__raw_payload = this._io.readBytes(1);
        this._raw_payload = KaitaiStream.processZlib(this._raw__raw_payload);
        KaitaiStream _io__raw_payload = new KaitaiStream(_raw_payload);
        this.payload = new Dummy(_io__raw_payload, this, _root);
    }
    [...]
    private Dummy payload;
    [....]
    public Dummy payload() { return payload; }

This is somewhere deep in the hierarchy of types of some data format and I would like to re-implement the type `Dummy` to apply some workaround behaviour. Seems easy to subclass that type, but it's not easy to get the parser to use it. Even if I subclass the parser itself and all types until the hierarchy where this `read` method is used, I can't provide an instance of my own type to be used instead of the default generated `Dummy`.

To make it easier to provide custom implementations, I would like to discuss two changes:

The easier part could be making the `read` method `protected` instead of `private` for those languages where this makes any difference, like Java and C++. This way one could re-implement that method and provide a derivation of `Dummy` this way. Depends on why it is `private` currently. Just because it's more correct to start with?

The second, and more complex, change is to not call CTORs of types directly anymore, but instead apply the [Factory method pattern](https://en.wikipedia.org/wiki/Factory_method_pattern) and provide a callback this way to derivations to provide their own implementation for types.  The above example would change to use the following line:

        this.payload = this.newDummy(_io__raw_payload, this, _root);

This is complex, because one needs to remember if such a callback needs to be generated for a used type and such. I guess generating the callback itself might not be that hard, because you already create the CTORs of that types somewhere else and such.

Using the factory method pattern, one would only need to override all types in the hierarchy to a type to be re-implemented and then provide custom implementations of types by implementing the special callbacks. But one would not need to implement `read` or such.

Is factory method pattern really necessary with public getters?

You already provide public getters for all properties and instances, so if I wanted to re-implement `Dummy` in the above example, I could do so and provide that implementation in the getter for `payload` in the parent type using `Dummy`. The problem with this is that the getter is surely called outside the default parse order and default parsing of `Dummy` still happened before. So one wasn't able to correct data really at the time a telegram is parsed and such. Seems to me that factory method pattern would make this all easier to understand and maintain.

Shouldn't workarounds be implemented in KSY preferable?

I think it depends, in my case I simply already had those in Java and thought of not re-implementing them in KSY again. One could think of workarounds or special behaviour including more business logic, depending on some app configuration or such. Might simply be too complex or hard to main for KSY. In the end, would simply cool to be able to choose. ;-)

What do you think of the proposed changes?

**Comment by tschoening** [comment]
@GreyCat provided a great suggestion in another discussion that seems to fit perfectly well to this enhancement:

> Using opaque types, you can basically use it as a loophole to implement any processing you want.
> Something like that: if your original ksy was like:

https://github.com/kaitai-io/kaitai_struct/issues/137#issuecomment-288058441

One can implement custom types in a target language of choice, using inheritance with KSY-types and such, and simply reference those in KSY to be used. Everything else is handled by KS already because of opaque types. The custom type can change the data in any way one likes and because of inheritance forward the changed data to the base class based on a KSY-type.

Opaque types were bad for further processing in the past, because KS didn't knew a thing about the inheritance and such, so one didn't have access to specific instances, fields etc. But now KS provides [casts](https://github.com/kaitai-io/kaitai_struct_compiler/issues/71): So in theory one could define the type as the custom one implemented outside of KSY and [cast](https://github.com/kaitai-io/kaitai_struct_compiler/issues/71) it to some base implemented in and usable by KSY using some `instance`. So other types in KSY wouldn't need to deal with the custom type as opaque type and the base KSY-type differently, but can only rely on the one and only KSY-type, sometimes directly parsed and sometimes cast from the custom type.

The important point regarding my former mentioned callbacks is, that it seems those are not needed at all. In KSY, one can simply define a custom type everywhere one likes and the KS compiler resolves those types already, regardless where they are in the hierarchy. And one needs a custom type always anyway to implement some different behaviour.

So let's look at an example based on the linked one by @GreyCat:

	seq:
	  - id: packet_1_that_needs_byte_2_added
		type: packet_unmangle
	  - id: packet_2_default
		type: packet
	types:
	  packet:
		...
	instances:
		packet1:
			value: packet_1_that_needs_byte_2_added.as<packet>
		packet2:
			value: packet_2_default

I think in former versions of KS without support for cast, `packet1` was a dead-end using in KSY, now it isn't anymore.

	public class PacketUnmangle extends Packet {
		private static KaitaiStream procCrazyStuff(KaitaiStream io) {
			byte[] orig = io.readBytes(255); // or whatever you need

			// my crude attempt at insertion of byte at position 1, shifting all array
			byte[] fixed = new byte[orig.length + 1];
			fixed[0] = orig[0];
			fixed[1] = 1; // magically added
			System.arraycopy(orig, 1, fixed, 2, orig.length - 1);

			return fixed;
		}


		public PacketUnmangle(KaitaiStream io) {
			super(PacketUnmangle.procCrazyStuff(io));
		}
	}

That might not work at all as it is, I'm just documenting my ideas here, but one should get the point. As this seems to provide a solution for what I suggested, I'm closing this for now.

**Comment by GreyCat** [comment]
This should work (after fixing `procCrazyStuff` to actually return `KaitaiStream`, it returns `byte[]` now, but that's trivial).

Another idea is to do `PacketUnmangle extends KaitaiStruct` and return custom KaitaiStream when asked for `_io()`. This will work even without casts:

```
seq:
  - id: packet_1_that_needs_byte_2_added
    type: packet_unmangle
types:
  packet:
    ...
instances:
  packet1:
    io: packet_1_that_needs_byte_2_added._io
    pos: 0
    type: packet
```

Of course, it this case you're limited to mangling the IO before the parsing occurs, you can't provide custom attributes in `PacketUnmangle` class itself.

**Comment by tschoening** [comment]
I have one problem and think this fits here best. My KSY using a cast throws the following error during compilation, even though without the cast and `fmt_oms_rec_pre_proc`, using the imported type directly, everything works. Is this some bug in type resolution using value instances?

> /types/fmt_clt_rec/instances/oms_rec/value: unable to find type 'fmt_oms_rec', searching from fmt_clt_recs::fmt_clt_rec

``` Yaml
meta:
  id:             fmt_clt_recs
  endian:         le
  imports:
    - fmt_oms_rec

seq:
  - id:     records
    type:   fmt_clt_rec
    repeat: eos

types:
  fmt_clt_rec:
    seq:
      - id:   length
        type: u1

      - id:   oms_rec_pre_proc
        size: oms_rec_length
        type: fmt_oms_rec_pre_proc

    instances:
      oms_rec:
        value:  oms_rec_pre_proc.as<fmt_oms_rec>
      oms_rec_length:
        value:  length - 6
```
