### ISSUE TITLE
Missing parenthesis around ternary operation in Javascript

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct_compiler#52]
This
`b1 * (1 == 0 ? 128 : 1)`
generates
`(this.b1 * 1 == 0 ? 128 : 1);`
instead of
`(this.b1 * (1 == 0 ? 128 : 1));`

**Comment by GreyCat** [comment]
Probably it's duplicate of https://github.com/kaitai-io/kaitai_struct_compiler/issues/39 ?

**Comment by GreyCat** [comment]
I've just checked, this particular bug seems to be solved, now it generates:

```javascript
      this._m_foo = (this.b1 * (1 == 0 ? 128 : 1));
```

Thus I'm closing this bug, and probably all other activities on this elusive operator parenthesis / priority question should go into https://github.com/kaitai-io/kaitai_struct/issues/69.
