### ISSUE TITLE
Try to reduce IOException in instance signatures in Java?

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#57]
I use a lot of instances in my KSY which actually don't parse anything from the stream, but more or less only work as some getter to map different conditions to some `enum` or such. The point is, that the data fields used in those instances are mostly getters or maybe other instances behaving the same, not parsing anything from the stream as well. So there's no way an `IOException` could be thrown on runtime, hence all signatures of all instances declare exactly that. And because it's a checked exception in Java, every caller of those instances need to handle or throw those unnecessary exceptions as well.

So how about finding ways to reduce this?

Looking at the code, `IOException` is simply added unconditionally in `JavaCompiler.instanceHeader` and currently one doesn't know much about what the instance does. But you already distinguish value and parsing instances in the specs, so wouldn't it be enoguh to forward the spec for the current instance to `instanceHeader`, check if it's a parsing one or not and add `IOException` only in case if it's a parsing one? This would work the same for all other languages, only the signature of `instanceHeader` would need to be changed.

Some examples of my KSY:

      is_header_none:
        value:  (control_info == 0x50) or
                (control_info == 0x51) or
                (control_info == 0x52) or
                (control_info == 0x69) or
                (control_info == 0x70) or
                (control_info == 0x71) or
                (control_info == 0x78) or
                (control_info == 0x79)

      header_type:
        value: "is_header_none    ? header_type::none   :
                (
                  is_header_short ? header_type::short  : header_type::long
                )"

...and what is generated for Java:

        private Boolean isHeaderNone;
        public Boolean isHeaderNone() throws IOException {
            if (this.isHeaderNone != null)
                return this.isHeaderNone;
            boolean _tmp = (boolean) ( ((controlInfo() == 80) || (controlInfo() == 81) || (controlInfo() == 82) || (controlInfo() == 105) || (controlInfo() == 112) || (controlInfo() == 113) || (controlInfo() == 120) || (controlInfo() == 121)) );
            this.isHeaderNone = _tmp;
            return this.isHeaderNone;
        }

        private HeaderType headerType;
        public HeaderType headerType() throws IOException {
            if (this.headerType != null)
                return this.headerType;
            this.headerType = isHeaderNone() ? HeaderType.NONE : isHeaderShort() ? HeaderType.SHORT : HeaderType.LONG;
            return this.headerType;
        }

**Comment by GreyCat** [comment]
Well, it's not like it is impossible, but from what I see, it is still fairly hard to do.

You can't just go "parse instances have `throws IOException`" and "value instances have no `throws`". You need to analyze whether there are any inner calls to anything that throws IOException:

* sequence getters never throw IOException
* parse instance getters always throw IOException
* value instances depend on whatever is used inside them

Given that Java is probably the only language that would ever need such mechanism (as "checked exceptions" are generally frowned upon nowadays), it is possible to implement this idea, but the benefits would be not that great => I'm inclined to consider this a "low priority" task.

**Comment by tschoening** [comment]
You're right of course, missed the main work part. :-)

What do you think about not throwing `IOException` at all anymore for all instances and instead catch and throw a `RuntimeException` always? As you say, checked exceptions are frowned upon, you don't have that concept in any other of your supported languages and it would only be "wrong" for parse instances. And not even that, the exception is not lost...

**Comment by tschoening** [comment]
That doesn't work easily either:

> Unreachable catch block for IOException. This exception is never thrown from the try statement body

If `IOException` is removed from the instance and an expression doesn't use any parsing logic throwing such an expression, the code doesn't compile with the former error. So one would need to check the statement if it throws an exception just like in the original suggestion.

**Comment by tschoening** [comment]
> [...]it is possible to implement this idea, but the benefits would be not that great[...]

You're right that the benefits for other languages wouldn't be that great, but for Java it would be huge. I'm just trying to integrate a KS generated parser into some existing codebase to replace the former parser and this `IOException` is driving me crazy, I need to handle/throw it in so many methods... :-/

Trying a new approach now: If parse instances are the only instances capable of throwing `IOException`, I could focus on capturing the exception only for those. This seems possible if `InstanceSpec` is forwarded to `instanceCheckCacheAndReturn`, which could start a `try` block, keep some status and add the `catch` in `instanceReturn` as needed. This way every expression possible of throwing an `IOException` in the instance is reached and the only influence on other languages would be a changed callback signature. Let's see...

**Comment by tschoening** [comment]
> If parse instances are the only instances capable of throwing IOException[...]

Wrong again, it's not only parse instances (e.g. called by value instances), but value instances can throw on their own as well:

         private Boolean reflectEof;
        public Boolean reflectEof() {
            if (this.reflectEof != null)
                return this.reflectEof;
            boolean _tmp = (boolean) (_io().isEof());
            this.reflectEof = _tmp;
            return this.reflectEof;
        }

But one should be able to detect that as well:

          case KaitaiStreamType =>
            attr.name match {
              case "size" => CalcIntType
              case "pos" => CalcIntType
              case "eof" => BooleanType
              case _ => throw new TypeMismatchError(s"called invalid attribute '${attr.name}' on expression of type $valType")
            }

**Comment by tschoening** [comment]
Closing this, because my cleanup has been merged and it was much easier this way.
