### ISSUE TITLE
Reading strings doesn't handle different character order?

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#65]
The format I'm currently working on has some byte range which could simply encode textual characters in ISO-8859-1. I have the following sentence in my spec:

> Like all multi byte fields the **last** character is transmitted **first**.

From looking at the Java runtime and the associated tests, this is currently not handled by the string reading functions. Or am I missing something? From my understanding you simply read bytes in order and create a string of them, all in read order of the bytes, which would violate my spec.

So do we need some "order" attribute for the individual characters to define which is the first one? Depending on that the runtime could simply reverse the read string in the easiest case.

It gets problematic for multi-byte encoding,  though.

On the other hand, isn't a string itself in its whole simply multi-byte data and needs to honour the endiannes, like an u8? So shouldn't data markes as little endian with a string always be read as my spec says, last char first? That would violate you current test, though. In theory, each individual char containing of multiple bytes would need to be read like the endianness tells as well?

**Comment by GreyCat** [comment]
Um, actually it doesn't seem to make any sense at all.

ISO8859-1 is a single-byte encoding. There's nothing to swap places and I've never ever seen anyone writing stream backwards (i.e. writing "dcba" to get "abcd"), motivating it with endianness. Technically, if anyone does that, that's not a huge problem to implement some method like `reverse` to reverse either the string or byte array before conversion to a string (hmm, by the way, we're definitely missing byte array -> string conversion method as well).

Things get slightly messier with multi-byte encodings, especially ones that do fixed amounts of bytes (>1) per character. That's UTF16, UTF32, etc. However, the humanity have already solved that problem by using encoding names like "UTF16LE" and "UTF16BE" to differentiate between two possible variants, i.e. "abcd" encoded as:

* `61 00 62 00 63 00 64 00` (UTF16LE)
* `00 61 00 62 00 63 00 64` (UTF16BE)

Note that, again, it does not reverse the string as a whole, it just reverses each multi-byte character in string.

So, if I'd think of improving the situation somehow, the best I can think of is treating encodings like "UTF16" specially by appending "BE" or "LE" suffix automatically based on current default endianness — however, that's not a very good idea either, as many encoding engines treat "UTF16" without BE and LE specially, i.e. expecting [BOM](http://en.wikipedia.org/wiki/Byte_order_mark) — and it's probably a bad idea to break their functionality there.

**Comment by tschoening** [comment]
> So, if I'd think of improving the situation somehow, the best I can think of is treating encodings like "UTF16" specially by appending "BE" or "LE" suffix automatically based on current default endianness[...]

Which wouldn't improve anything for me regarding the sentence in the spec. :-) I find that sentence a bit strange es well and have no real world example for such data currently, so we can simply do nothing for now. Else the `reverse` option would be the only form which I would benefit, because I only have single byte strings and need to reverse... At least if the sentence in the string is not wrong at all.

**Comment by GreyCat** [comment]
I strongly think that it's just some figure of speech and they didn't really mean that they transmit strings in reverse order of characters. May be they meant that (if) they use UTF16, they use little-endian encoding, thus "0x0061" codepoint is transmitted as `61 00`.

**Comment by tschoening** [comment]
I have two of those sentences: :-)

> NOTE 1 A text string (like all other mutibyte data) is transmitted “Least significant byte first”

Will ask another source if he knows some more details...

**Comment by GreyCat** [comment]
I take that is a translation from German? May be there are some translation issues?

**Comment by tschoening** [comment]
It's the original English text of an official industry standard. Might was German in the past, don't know, at least it's no translation I made. Just C&P from the spec.

**Comment by GreyCat** [comment]
Just heard a talk from some SUSE documentation guy yesterday. He said that they basically write all their documentation in German, and then turn it to some external translation agency, which does translations into English and tons of other languages as well. And sometimes it turns out that translations are, well, not quite as good from technical point of view. May be it's the same case here?

**Comment by koczkatamas** [comment]
I think we are talking about this standard: http://www.m-bus.com/

The original quote can be found in it verbatim: http://www.m-bus.com/files/MBDOC48.PDF

We should find either an example communication and/or a parser library and see how does it work, that will probably decide this debate.

((Back then my big-endian / little-endian parsing proof-of-code read data by reading byte array and reversing the whole array it if it was big endian. Maybe they also implemented this 'generic endianess-independent' byte array reading method too. But it's really weird for me too. I never met any file format storing string values this way.))

**Comment by tschoening** [comment]
> I think we are talking about this standard: http://www.m-bus.com/

At least somewhat/in general, yes, not sure currently how my "wireless m-bus" differs from you document, but a lot seems quite similar. I have forgotten that there's an example in my spec, which I would like to quote, because I think it "proves" the strange string encoding. Look at the HEX codes of "igal" and their order and please correct me if I misunderstood things. But it looks to me the chars are "reversed". :-)

> C.2 Plain text units
> In case of VIF = 7Ch / FCh the applied unit is represented by the following ASCII string with the length
given in the first byte. The rightmost character is transmitted first. This plain text VIF allows the user to
code units that are not included in the VIF tables.

> Table C.2 — Data record structure for plain text VIF usage
> DIB VIB ASCII length ASCII string Value

> Example (all values are hex):
0C DIF means 8 digit BCD value
FC VIF means plain text VIF following
A2 VIFE means “per hour”
73 VIFE means “*10E-3”
04 ASCII length means 4 byte ASCII string following
6C 61 67 69 ASCII string means “igal”
26 08 42 75 Value = 75420826
Coded value = 75420826 igal/h * 10E-3 ( = 75420,826 Imperial Gallons / hour )

`6C` is a lower case"L" already, last char first. :-)

![Some screenshot as well...](https://picload.org/image/rocidrll/13757-32012varlengthstrings.png)

**Comment by GreyCat** [comment]
Indeed, a very strange encoding. I've only seen something remotely resembling that once: sometimes when using FourCC-like method of data tagging, people use integers to read 4-byte ASCII tag strings. And given that they usually do use platform-dependent integers, which, for x86 makes them little-endian, this effectively generates code like that:

```cpp
uint32_t four_cc = read_uint32(...); // reads little-endian 
if (four_cc == 0x46464952) { // == "RIFF"
    ...
}
```

Note that "RIFF" is 52 49 46 46, and 0x46464952 is that bytes backwards due to exactly 4-byte string is being read as 4-byte little-endian integer.

However, it this particular case I guess it's easier to implement `.reverse` for strings. Implementation should be pretty much trivial:

* For Java, it's `new StringBuilder(x).reverse().toString()`
* For Ruby, it's `x.reverse`
* For Python, it's `x[::-1]`

i.e. most languages have something like that in stdlib anyway.

**Comment by tschoening** [comment]
> However, it this particular case I guess it's easier to implement .reverse for strings.

Additionally I've thought of providing an attribute `reverse: true` like e.g. `encoding: ...`. But I guess my use case is somewhat to special and in such a use case I even see benefit of working with custom types like the following:

    str_reversed:
      seq:
        - id:       value_from_stream
          size-eos: true
          type:     str
          encoding: ISO-8859-1
          doc:      [...]
  
      # str_reversed:
      instances:
        value:
          value:  value_from_stream.reverse
          doc:    [...]

This way one has both the original and the reversed value for debugging purpose and such.

C++ is not implemented currently, but I think we can handle this on the actual pull request. Reopen if you disagree...
