### ISSUE TITLE
Resolving multiple _parent doesn't seem to work.

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#68]
I get the following error message:

> Exception in thread "main" java.lang.RuntimeException: Unable to access are_vdbs_decrypted_wo_enc_mode in List(fmt_oms_rec, fmt_oms_apl_vdb_header) context

for the following two variants of my KSY:

                    (_parent.are_vdbs_decrypted_wo_enc_mode)                                and
                    (_parent.vdbs_decrypted_wo_enc_mode.size                    == 1)

[...]

                    (_parent._parent._parent._parent._parent.are_vdbs_decrypted_wo_enc_mode)                                and
                    (_parent.vdbs_decrypted_wo_enc_mode.size                    == 1)

The first `_parent` resolving to `fmt_oms_apl_vdb_header` is correct, all others not. I thought I would be able to climb the hierarchy more than one level using `_parent`, but doesn't look so currently. Not sure where the problem is, if only the first `_parent` is resolved and all others ignored or if they all resolve to the same target type...

This is a bit related to #38 and #49, as I already tried to fix some shortcomings of the current implementation there. As it didn't work before, I'm pretty sure to at least not have broken things. ;-)

**Comment by GreyCat** [comment]
With recent fixes on #38 and #49, I don't see a problem with multiple `_parent._parent._parent` invocations anymore as well. Can you check if this problem still persists for you?

**Comment by tschoening** [comment]
It's fixed for me as well, great, thanks.

**Comment by GreyCat** [comment]
I'll try to add more tests on `_parent` in near future, just to be sure.
