### ISSUE TITLE
Implement casts

### ISSUE THREAD

**Issue by DarkDimius** [kaitai-io/kaitai_struct_compiler#71]
Use-case: there's an array of objects, which could have different types.
If I somehow know that specific object has a specific type I it would be nice to be able to cast it and take advantage of a more precise type.

example: https://gist.github.com/DarkDimius/eaed558f58b986ece94d481a1e9a7365

**Comment by GreyCat** [comment]
As we discussed in the chat, probably `expr.as<T>`, where `T` is the type reference would be the preferred syntax.

**Comment by GreyCat** [comment]
Cc @tschoening: you might be interested in this feature as well?

**Comment by tschoening** [comment]
Yes, I have similar use cases and already provide different type checking getters to make casts in higher levels of my app easier. So for some often used/important types I know about those at runtime already and could provide that information to KSY, like I do already in Java. Only that I would benefit in all target languages and might implement trivial data usage in KSY already.

**Comment by GreyCat** [comment]
The basic implementation is here. New test [switch_cast](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/switch_cast.ksy) illustrates the most common use-case: `opcodes[x].body` is a switchable type, which is returned as generic KaitaiStruct-compatible. When we're sure that a certain element is of some specific type, we can enforce a cast, i.e. something like `opcodes[0].body.as<strval>`.

Tested and works for C++, C# and Java, for everyone else it's just a transparent no-op. Note that C++ uses `static_cast<...>` on a pointer type, so there would be no cast exception thrown in case when things go wrong. C# and Java throw "bad cast" exceptions properly (see `err_cast` value instance).

**Comment by GreyCat** [comment]
Again, the functionality is here, tests and there, so I guess we can close this one.
