### ISSUE TITLE
In error message, indicate ksy line number

### ISSUE THREAD

**Issue by DarkDimius** [kaitai-io/kaitai_struct_compiler#73]
```
KS compilation error: java.lang.RuntimeException: Unable to access value in List(Nat) context
```

Isn't very helpful if the `ksy` file is big and it's not clear where does the error come from.

**Comment by GreyCat** [comment]
Accessing unknown names in context of some user-defined type now returns a much clearer message like that:

```
/seq/1/if: unable to access 'value' in nat context
```

This includes precise location of a problem (i.e. `/seq/1/if` - top level type, `seq` attribute sequence, second attribute (`1`), expression used in `if`).

I'm considering it closed, please reopen if any concerns arise.
