### ISSUE TITLE
When compiling to python, the doc elements aren't exported into a docstring. 

### ISSUE THREAD

**Issue by DarkLinkXXXX** [kaitai-io/kaitai_struct_compiler#76]
One line docstrings should be defined like this. 
```
def kos_root():
    """Return the pathname of the KOS root directory."""
    global _kos_root
    if _kos_root: return _kos_root
```

Multi-line docstrings should be defined this way. 
```
def complex(real=0.0, imag=0.0):
    """Form a complex number.

    Keyword arguments:
    real -- the real part (default 0.0)
    imag -- the imaginary part (default 0.0)
    """
    if imag == 0.0 and real == 0.0:
        return complex_zero
```

**Comment by GreyCat** [comment]
Thanks! As far as I remember, the problem with Python was docstrings for `seq` attributes: see https://github.com/kaitai-io/kaitai_struct/issues/20#issuecomment-258879699

**Comment by GreyCat** [comment]
I've implemented most of the Python docstring support, it seems to work now (except for `seq` attributes, unfortunately) — I guess it's better than nothing. Could you take a look?

**Comment by GreyCat** [comment]
Closing this one: it looks somewhat done now.
