### ISSUE TITLE
Syntax error in KSY breaks compilation, but does not change exit code in shell

### ISSUE THREAD

**Issue by FilipDominec** [kaitai-io/kaitai_struct_compiler#83]
Syntax error in KSY breaks compilation, but does not change exit code in shell. 

Thus, an usual linux command-line construct like this

    kaitai-struct-compiler syntaxdef.ksy -t python   &&   python test.py

executes the python command always, even if ```syntaxdef.ksy``` is invalid. I guess the fix is just a few lines of code.

**Comment by GreyCat** [comment]
Makes sense, thanks!
I've fixed it in https://github.com/kaitai-io/kaitai_struct_compiler/commit/b1890d6b4d17d6b930373de435cf6ad451990617 — if you'll succeed in building this, please take a look.

**Comment by GreyCat** [comment]
I guess this is fixed, so I'm closing it. Feel free to reopen if there are any questions left.
