### ISSUE TITLE
Ocaml support

### ISSUE THREAD

**Issue by osmoc** [kaitai-io/kaitai_struct_compiler#87]
Is there roadmap for planned extension of supported target languages? I'm particularly interested in Ocaml for example but it would be great to have an overview if particular language is planned to be supported, will be supported if someone send a patch, won't be supported ever etc.

**Comment by GreyCat** [comment]
That's a good idea to create one. So far we've just had people creating issues about new language support in [issues](https://github.com/kaitai-io/kaitai_struct/issues/). I'll probably move this issue there and create a label for new language requests, so it would be easy to find all requested languages.

**Comment by osmoc** [comment]
Thanks for quick follow-up.

**Comment by GreyCat** [comment]
Moved this one to https://github.com/kaitai-io/kaitai_struct/issues/182 — please continue there.
