### ISSUE TITLE
perl compiler doesn't work with --debug

### ISSUE THREAD

**Issue by tecknicaltom** [kaitai-io/kaitai_struct_compiler#88]
When compiling with -t perl, adding --debug causes the compiler to error with:
  an implementation is missing

It appears that the perl compiler does not properly support the functionality needed to emit debug information.

**Comment by GreyCat** [comment]
Debug information is very language dependent and thus it is added to match particular implementation of visualizer / IDE / tools. There are no Perl tools so far → no debug information. If you want one, let's discuss whatever is needed.

**Comment by GreyCat** [comment]
Given lack of interest for ~1.5 years, I'm closing this for now. Please reopen an issue fro `--debug` support in Perl in [main repo](https://github.com/kaitai-io/kaitai_struct/issues), if this would be needed.
